name: 334Ranker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
          
      - run: |
          python -V
          pip install get-chrome-driver --upgrade
          pip install -r requirements.txt
          
      - name: Run Python
        env:
          URL: ${{ secrets.URL }}
        run: python app.py
