name: 334Ranker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - run: |
          python -m pip install --upgrade pip
          pip install get-chrome-driver --upgrade
          pip install -r requirements.txt
          
      - name: Run Python
        env:
          URL: ${{ secrets.URL }}
          TZ: "Asia/Tokyo"
        run: python app.py
