name: 334Ranker

on:
  #schedule:
  #  - cron:  '52 17 * * *'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - run: |
          pip install get-chrome-driver --upgrade
          pip install -r requirements.txt
          
      - name: Run Python
        env:
          CK: ${{ secrets.CK }}
          CS: ${{ secrets.CS }}
          AT: ${{ secrets.AT }}
          AS: ${{ secrets.AS }}
          BT: ${{ secrets.BT }}
          URL: ${{ secrets.URL }}
          TZ: "Asia/Tokyo"
        run: python app.py
